version: "3.8"

volumes:
  forumlearning-mysqldata:
  letsencrypt:

services:
  
  mysqldb:
    restart: always
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    environment:
      - MYSQL_DATABASE=forum_learning
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - forumlearning-mysqldata:/var/lib/mysql
      - ./mysqldump-folder/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysqldump-folder/test_data.sql:/docker-entrypoint-initdb.d/2.sql

  identity:
    container_name: forum_learning-identity
    build: ./identity/
    restart: always
    environment: 
      - GIN_MODE=release
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=forum_learning
      - API_SECRET_KEY=oLHXrfYyie-npLidoqc6jW5_l4fthb08wtw4lPQ2e67ZUH9yvg7XBrTXQzhElFWKZYSYd18kqs5wB6_18t1y0Pq0Ug1OSSnFTTsepSwuxenoacwb2_iebidmx5_MbQsAdiXBYZ4B4zg9IhqEtKhQv6kGJXu1Ai-UarPqpMOFnuxiwLJ1XGQCfQPHieXj-afKiPdXmcqfMx2krHSILTn-9ZErQtOijNM1LS7am-Gpn3RTY29LHXPSayrfdsQQ2UidjB6GttP4LmePA75kXy2hZsA2iilTrSY43FsQCxrgWRbmAhmw65YKP_mVyQhan0lvfS0a6GCOfFoJWSB_BJc8Ft1shtDa2lqJqxuajFwfHUU4yzemvl0UUJ3yLlHrCm8pAwiR7zeih53FIsLl_gz6uhICO3Q0qDjYgDK7_GEeGw9OHb_rkA52fHq_rwVlectvgCWY9_DCNXZVUcWz5y7i9evzCDoXgafDUwWq3-QjnEcl7LuyaASOR666Er9CcIhQxAtqK0DFfVtNM4gxE3aGWb8jdvv4oijGkenP2_wqkP8Sd7A7a6YAAZvueqNlK_mRGChgZ6Tg9He4jKvgKEExpdtPekuNWLUnrN0nfVy06Ab11QP4wjiBEh8zWGe5vuQlNUzpEI2vJt2ofGwC6XdgaS0cCmc_C9EnxLypq8NUTck
    volumes: 
      - ./log/identity/:/src/log/
    depends_on: 
      - mysqldb

  forum:
    container_name: forum_learning-forum
    build: ./forum/
    restart: always
    environment: 
      - GIN_MODE=release
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=forum_learning
    volumes: 
      - ./log/forum/:/src/log/
    depends_on: 
      - mysqldb
  
  api_gateway:
    container_name: forum_learning-api_gateway
    build: ./api-gateway/
    restart: always
    environment: 
      - GIN_MODE=debug
    volumes: 
      - ./log/api_gateway/:/src/log/
      - ./api-gateway-config/:/src/config/
    ports:
      - "8080:8080"
      
  front-end_client:
    container_name: forum_learning-front_end_client
    build: ./front-end_client
    restart: always
    environment:
      - SECRET_KEY=BF6Pco_XRPBqOU-ptgdjWaIj_QzLzFX4Ce3xTShtaoSDzSP4Kswm47RIJDenROuaiJAlVDw5ODuZwwj7yMfBwvWAAIeDZd5iNPaVsMqtbVgtyn2l-DhFnzRpeFID08b6gDFI-jgnyFnHXBpDp6O9HHTpHfVx7vVZZGQgvh_e_jIZcsenZsrOd_Ezr_7ptbgaW24bx8D8hMfdNCpObOO2wGdg_brVwx_8MUZLqxQLmPbssb9YrZriHkELMteplmrXsz7h9gxI_aeZavuv6ExUyTqzCfPgSskuba8QRpWXP6hjw-4blsTQ7upCQZ1EM-2pTSCsDx6tEmb2yC6YIy03E-b9LwmlKJwj-bGNWAjQ05jfvbaAJmS76Z1LU-Cq_0v03vzwXAWWkJt6BRSKBRULDYo53Q_Q-UNPr2O4X3WJDCjxvtTXJrOwmK_J3FkdT_g0uaCtbX9RhtD3xFjZTbvL2YVK69V0EbvAxOuhy0ues4T0hzxOqjNZ9KDgEIsBs6rq_dzQ48XbTOz1slNZHjBCfTxzbbKoD03pxSIpte8nl2wXxiC-Hayl9SakexrQInSJRvx-xnSInSJu4wwWNe2ozcleYCKrwz-eI2Wzjfoe12NgmOo2K8IJl7YoEqMJU2Fem9f1Z-PfePS-guk351_j-2pX8PsNKBesLThAY-PlWkI
      - API_SECRET_KEY=oLHXrfYyie-npLidoqc6jW5_l4fthb08wtw4lPQ2e67ZUH9yvg7XBrTXQzhElFWKZYSYd18kqs5wB6_18t1y0Pq0Ug1OSSnFTTsepSwuxenoacwb2_iebidmx5_MbQsAdiXBYZ4B4zg9IhqEtKhQv6kGJXu1Ai-UarPqpMOFnuxiwLJ1XGQCfQPHieXj-afKiPdXmcqfMx2krHSILTn-9ZErQtOijNM1LS7am-Gpn3RTY29LHXPSayrfdsQQ2UidjB6GttP4LmePA75kXy2hZsA2iilTrSY43FsQCxrgWRbmAhmw65YKP_mVyQhan0lvfS0a6GCOfFoJWSB_BJc8Ft1shtDa2lqJqxuajFwfHUU4yzemvl0UUJ3yLlHrCm8pAwiR7zeih53FIsLl_gz6uhICO3Q0qDjYgDK7_GEeGw9OHb_rkA52fHq_rwVlectvgCWY9_DCNXZVUcWz5y7i9evzCDoXgafDUwWq3-QjnEcl7LuyaASOR666Er9CcIhQxAtqK0DFfVtNM4gxE3aGWb8jdvv4oijGkenP2_wqkP8Sd7A7a6YAAZvueqNlK_mRGChgZ6Tg9He4jKvgKEExpdtPekuNWLUnrN0nfVy06Ab11QP4wjiBEh8zWGe5vuQlNUzpEI2vJt2ofGwC6XdgaS0cCmc_C9EnxLypq8NUTck
      - API_BASE_URL=wildangbudhi.com
    volumes: 
      - ./front-end_client/app/:/app
    ports: 
      - "81:5000"
    
  front-end_admin:
    container_name: forum_learning-front_end_admin
    build: ./front-end_admin
    restart: always
    volumes: 
      - ./front-end_admin/app/:/app
    ports: 
      - "82:5000"
      
  nginx:
    container_name: forum_learning-nginx
    build: ./nginx/prod
    entrypoint: "/root/init.sh"
    restart: always
    environment: 
      - NGINX_HOST_MAIN=wildangbudhi.com
      - NGINX_HOST_ADMIN=admin.wildangbudhi.com
    ports: 
      - "80:80" 
      - "443:443"
